=== carter15nba/warhammer-army-builder/WarhammerArmyBuilder/Resources/XML/Warhammer.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Warhammer.xsd
    Created on : 11. januar 2011, 12.46
    Author     : Glenn Rune StrandbrÃ¥ten
    Description:
        This document defines the structure of the Warhammer Race xml schema.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">
    <xsd:element name="Race">
      <xsd:complexType mixed="true">
          <xsd:sequence>
              <xsd:element name="Name" type="xsd:string"/>
              <xsd:element name="Unit" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Name" type="xsd:string"/>
                        <xsd:element name="Movement" type="xsd:string"/>
                        <xsd:element name="WeaponSkill" type="xsd:string"/>
                        <xsd:element name="BallisticSkill" type="xsd:string"/>
                        <xsd:element name="Strength" type="xsd:string"/>
                        <xsd:element name="Toughness" type="xsd:string"/>
                        <xsd:element name="Wounds" type="xsd:string"/>
                        <xsd:element name="Initiative" type="xsd:string"/>
                        <xsd:element name="Attack" type="xsd:string"/>
                        <xsd:element name="Leadership" type="xsd:string"/>
                        <xsd:element name="Type" type="xsd:string"/>
                        <xsd:element name="Mount" minOccurs="0" maxOccurs="3">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Name" type="xsd:string"/>
                                    <xsd:element name="Movement" type="xsd:string"/>
                                    <xsd:element name="WeaponSkill" type="xsd:string"/>
                                    <xsd:element name="BallisticSkill" type="xsd:string"/>
                                    <xsd:element name="Strength" type="xsd:string"/>
                                    <xsd:element name="Toughness" type="xsd:string"/>
                                    <xsd:element name="Wounds" type="xsd:string"/>
                                    <xsd:element name="Initiative" type="xsd:string"/>
                                    <xsd:element name="Attack" type="xsd:string"/>
                                    <xsd:element name="Leadership" type="xsd:string"/>
                                    <xsd:element name="Type" type="xsd:string"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="Crew" minOccurs="0" maxOccurs="3">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Name" type="xsd:string"/>
                                    <xsd:element name="Movement" type="xsd:string"/>
                                    <xsd:element name="WeaponSkill" type="xsd:string"/>
                                    <xsd:element name="BallisticSkill" type="xsd:string"/>
                                    <xsd:element name="Strength" type="xsd:string"/>
                                    <xsd:element name="Toughness" type="xsd:string"/>
                                    <xsd:element name="Wounds" type="xsd:string"/>
                                    <xsd:element name="Initiative" type="xsd:string"/>
                                    <xsd:element name="Attack" type="xsd:string"/>
                                    <xsd:element name="Leadership" type="xsd:string"/>
                                    <xsd:element name="Type" type="xsd:string"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== carter15nba/warhammer-army-builder/trunk/WarhammerArmyBuilder/Resources/XML/RaceTemplate.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!--
    Document   : RaceTemplate.xml
    Created on : 11. januar 2011, 11:42
    Author     : Glenn Rune Strandbråten
    Description:
        This document contains data associated with a Warhammer Race, its units
        and the units attributes. These data are used by the
        WarhammerArmyBuilder software to populate the armies and aquire the
        neccessary information.
-->

<Race xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com Warhammer.xsd">
    <Name></Name>
    <Unit>
        <Name></Name>
        <Movement></Movement>
        <WeaponSkill></WeaponSkill>
        <BallisticSkill></BallisticSkill>
        <Strength></Strength>
        <Toughness></Toughness>
        <Wounds></Wounds>
        <Initiative></Initiative>
        <Attack></Attack>
        <Leadership></Leadership>
        <Type></Type>
    </Unit>
    <Unit>
        <Name></Name>
        <Movement></Movement>
        <WeaponSkill></WeaponSkill>
        <BallisticSkill></BallisticSkill>
        <Strength></Strength>
        <Toughness></Toughness>
        <Wounds></Wounds>
        <Initiative></Initiative>
        <Attack></Attack>
        <Leadership></Leadership>
        <Type></Type>
        <Mount>
            <Name></Name>
            <Movement></Movement>
            <WeaponSkill></WeaponSkill>
            <BallisticSkill></BallisticSkill>
            <Strength></Strength>
            <Toughness></Toughness>
            <Wounds></Wounds>
            <Initiative></Initiative>
            <Attack></Attack>
            <Leadership></Leadership>
            <Type></Type>
        </Mount>
    </Unit>
    <Unit>
        <Name></Name>
        <Movement></Movement>
        <WeaponSkill></WeaponSkill>
        <BallisticSkill></BallisticSkill>
        <Strength></Strength>
        <Toughness></Toughness>
        <Wounds></Wounds>
        <Initiative></Initiative>
        <Attack></Attack>
        <Leadership></Leadership>
        <Type></Type>
        <Crew>
            <Name></Name>
            <Movement></Movement>
            <WeaponSkill></WeaponSkill>
            <BallisticSkill></BallisticSkill>
            <Strength></Strength>
            <Toughness></Toughness>
            <Wounds></Wounds>
            <Initiative></Initiative>
            <Attack></Attack>
            <Leadership></Leadership>
            <Type></Type>
        </Crew>
    </Unit>
</Race>

=== carter15nba/warhammer-army-builder/WarhammerArmyBuilder/Resources/XML/RaceTemplate.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!--
    Document   : RaceTemplate.xml
    Created on : 11. januar 2011, 11:42
    Author     : Glenn Rune Strandbråten
    Description:
        This document contains data associated with a Warhammer Race, its units
        and the units attributes. These data are used by the
        WarhammerArmyBuilder software to populate the armies and aquire the
        neccessary information.
-->

<Race xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com Warhammer.xsd">
    <RaceName></RaceName>
    <Unit>
        <UnitName></UnitName>
        <Movement></Movement>
        <WeaponSkill></WeaponSkill>
        <BallisticSkill></BallisticSkill>
        <Strength></Strength>
        <Toughness></Toughness>
        <Wounds></Wounds>
        <Initiative></Initiative>
        <Attack></Attack>
        <Leadership></Leadership>
        <Type></Type>
    </Unit>
    <Unit>
        <UnitName></UnitName>
        <Movement></Movement>
        <WeaponSkill></WeaponSkill>
        <BallisticSkill></BallisticSkill>
        <Strength></Strength>
        <Toughness></Toughness>
        <Wounds></Wounds>
        <Initiative></Initiative>
        <Attack></Attack>
        <Leadership></Leadership>
        <Type></Type>
        <Mount>
            <MountName></MountName>
            <Movement></Movement>
            <WeaponSkill></WeaponSkill>
            <BallisticSkill></BallisticSkill>
            <Strength></Strength>
            <Toughness></Toughness>
            <Wounds></Wounds>
            <Initiative></Initiative>
            <Attack></Attack>
            <Leadership></Leadership>
            <Type></Type>
        </Mount>
    </Unit>
    <Unit>
        <UnitName></UnitName>
        <Movement></Movement>
        <WeaponSkill></WeaponSkill>
        <BallisticSkill></BallisticSkill>
        <Strength></Strength>
        <Toughness></Toughness>
        <Wounds></Wounds>
        <Initiative></Initiative>
        <Attack></Attack>
        <Leadership></Leadership>
        <Type></Type>
        <Crew>
            <CrewName></CrewName>
            <Movement></Movement>
            <WeaponSkill></WeaponSkill>
            <BallisticSkill></BallisticSkill>
            <Strength></Strength>
            <Toughness></Toughness>
            <Wounds></Wounds>
            <Initiative></Initiative>
            <Attack></Attack>
            <Leadership></Leadership>
            <Type></Type>
        </Crew>
    </Unit>
</Race>
